// SPDX-FileCopyrightText: 2025 terkala <appleorange64@gmail.com>
//
// SPDX-License-Identifier: MIT

using Content.Client.UserInterface.Controls;
using Content.Shared.Medical.Surgery;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Client.GameObjects;

namespace Content.Client.Medical.Surgery;

[GenerateTypedNameReferences]
public sealed partial class SurgeryWindow : Content.Client.UserInterface.Controls.FancyWindow
{
    public event Action<SurgeryLayer>? OnLayerChanged;
    public event Action<NetEntity>? OnStepSelected;

    public SurgeryLayer CurrentLayer { get; private set; } = SurgeryLayer.Skin;
    private readonly IEntityManager _entMan;

    public SurgeryWindow(IEntityManager entMan)
    {
        RobustXamlLoader.Load(this);
        _entMan = entMan;

        SkinTabButton.OnPressed += _ => SetLayer(SurgeryLayer.Skin);
        TissueTabButton.OnPressed += _ => SetLayer(SurgeryLayer.Tissue);
        OrganTabButton.OnPressed += _ => SetLayer(SurgeryLayer.Organ);
    }

    private void SetLayer(SurgeryLayer layer)
    {
        CurrentLayer = layer;
        OnLayerChanged?.Invoke(layer);
        UpdateLayerButtons();
    }

    private void UpdateLayerButtons()
    {
        SkinTabButton.Pressed = CurrentLayer == SurgeryLayer.Skin;
        TissueTabButton.Pressed = CurrentLayer == SurgeryLayer.Tissue;
        OrganTabButton.Pressed = CurrentLayer == SurgeryLayer.Organ;
    }

    public void UpdateState(SurgeryBoundUserInterfaceState state)
    {
        UpdateLayerButtons();

        StepsContainer.RemoveAllChildren();

        List<NetEntity> steps;
        bool layerAccessible = false;

        switch (CurrentLayer)
        {
            case SurgeryLayer.Skin:
                steps = state.SkinSteps;
                layerAccessible = true; // Skin layer is always accessible
                break;
            case SurgeryLayer.Tissue:
                steps = state.TissueSteps;
                layerAccessible = state.SkinRetracted; // Tissue requires skin to be retracted
                break;
            case SurgeryLayer.Organ:
                steps = state.OrganSteps;
                // Organ layer is accessible if tissue is retracted and bones are sawed OR smashed
                // Bones don't need to be sawed - surgeons can skip steps if needed
                layerAccessible = state.TissueRetracted && (state.BonesSawed || state.BonesSmashed);
                break;
            default:
                steps = new List<NetEntity>();
                break;
        }

        if (!layerAccessible)
        {
            var label = new Robust.Client.UserInterface.Controls.Label 
            { 
                Text = Loc.GetString("surgery-window-layer-inaccessible", 
                    ("layer", Loc.GetString($"surgery-window-layer-{CurrentLayer.ToString().ToLower()}")))
            };
            StepsContainer.AddChild(label);
            return;
        }

        if (steps.Count == 0)
        {
            var label = new Robust.Client.UserInterface.Controls.Label { Text = Loc.GetString("surgery-window-no-steps") };
            StepsContainer.AddChild(label);
            return;
        }

        foreach (var stepNetEntity in steps)
        {
            var stepEntity = _entMan.GetEntity(stepNetEntity);
            var button = new Robust.Client.UserInterface.Controls.Button
            {
                Text = _entMan.GetComponent<MetaDataComponent>(stepEntity).EntityName,
                HorizontalExpand = true
            };

            button.OnPressed += _ => OnStepSelected?.Invoke(stepNetEntity);
            StepsContainer.AddChild(button);
        }
    }
}

