// SPDX-FileCopyrightText: 2025 terkala <appleorange64@gmail.com>
//
// SPDX-License-Identifier: MIT

using Content.Client.UserInterface.Controls;
using Content.Shared.Medical.Surgery;
using Content.Shared._Shitmed.Targeting;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;

namespace Content.Client.Medical.Surgery;

[GenerateTypedNameReferences]
public sealed partial class SurgeryWindow : Content.Client.UserInterface.Controls.FancyWindow
{
    public event Action<SurgeryLayer>? OnLayerChanged;
    public event Action<NetEntity>? OnStepSelected;
    public event Action<TargetBodyPart?>? OnBodyPartSelected;

    public SurgeryLayer CurrentLayer { get; private set; } = SurgeryLayer.Skin;
    private readonly IEntityManager _entMan;
    private readonly Dictionary<TargetBodyPart, TextureButton> _bodyPartControls;
    private TargetBodyPart? _selectedBodyPart;

    public SurgeryWindow(IEntityManager entMan)
    {
        RobustXamlLoader.Load(this);
        _entMan = entMan;

        _bodyPartControls = new Dictionary<TargetBodyPart, TextureButton>
        {
            { TargetBodyPart.Head, HeadButton },
            { TargetBodyPart.Torso, ChestButton },
            { TargetBodyPart.LeftArm, LeftArmButton },
            { TargetBodyPart.LeftHand, LeftHandButton },
            { TargetBodyPart.RightArm, RightArmButton },
            { TargetBodyPart.RightHand, RightHandButton },
            { TargetBodyPart.LeftLeg, LeftLegButton },
            { TargetBodyPart.LeftFoot, LeftFootButton },
            { TargetBodyPart.RightLeg, RightLegButton },
            { TargetBodyPart.RightFoot, RightFootButton },
        };

        foreach (var bodyPartButton in _bodyPartControls)
        {
            bodyPartButton.Value.MouseFilter = MouseFilterMode.Stop;
            bodyPartButton.Value.OnPressed += _ => SetActiveBodyPart(bodyPartButton.Key);
        }

        SkinTabButton.OnPressed += _ => SetLayer(SurgeryLayer.Skin);
        TissueTabButton.OnPressed += _ => SetLayer(SurgeryLayer.Tissue);
        OrganTabButton.OnPressed += _ => SetLayer(SurgeryLayer.Organ);
    }

    private void SetActiveBodyPart(TargetBodyPart part)
    {
        _selectedBodyPart = part;
        UpdateBodyPartButtons();
        OnBodyPartSelected?.Invoke(part);
    }

    private void UpdateBodyPartButtons()
    {
        foreach (var (part, button) in _bodyPartControls)
        {
            button.Pressed = part == _selectedBodyPart;
        }
    }

    private void SetLayer(SurgeryLayer layer)
    {
        CurrentLayer = layer;
        OnLayerChanged?.Invoke(layer);
        // Update buttons will be called from UpdateState with proper state
    }

    public void UpdateState(SurgeryBoundUserInterfaceState state)
    {
        // Update selected body part from state
        if (state.SelectedTargetBodyPart != _selectedBodyPart)
        {
            _selectedBodyPart = state.SelectedTargetBodyPart;
            UpdateBodyPartButtons();
        }

        // Update layer buttons - disable if not accessible
        UpdateLayerButtons(state);

        StepsContainer.RemoveAllChildren();

        List<NetEntity> steps;
        bool layerAccessible = false;

        switch (CurrentLayer)
        {
            case SurgeryLayer.Skin:
                steps = state.SkinSteps;
                layerAccessible = true; // Skin layer is always accessible
                break;
            case SurgeryLayer.Tissue:
                steps = state.TissueSteps;
                layerAccessible = state.CanAccessTissueLayer; // Use state flag
                break;
            case SurgeryLayer.Organ:
                steps = state.OrganSteps;
                layerAccessible = state.CanAccessOrganLayer; // Use state flag
                break;
            default:
                steps = new List<NetEntity>();
                break;
        }

        if (!layerAccessible)
        {
            var label = new Robust.Client.UserInterface.Controls.Label 
            { 
                Text = Loc.GetString("surgery-window-layer-inaccessible", 
                    ("layer", Loc.GetString($"surgery-window-layer-{CurrentLayer.ToString().ToLower()}")))
            };
            StepsContainer.AddChild(label);
            return;
        }

        if (steps.Count == 0)
        {
            var label = new Robust.Client.UserInterface.Controls.Label { Text = Loc.GetString("surgery-window-no-steps") };
            StepsContainer.AddChild(label);
            return;
        }

        foreach (var stepNetEntity in steps)
        {
            var stepEntity = _entMan.GetEntity(stepNetEntity);
            var button = new Robust.Client.UserInterface.Controls.Button
            {
                Text = _entMan.GetComponent<MetaDataComponent>(stepEntity).EntityName,
                HorizontalExpand = true
            };

            button.OnPressed += _ => OnStepSelected?.Invoke(stepNetEntity);
            StepsContainer.AddChild(button);
        }
    }

    private void UpdateLayerButtons(SurgeryBoundUserInterfaceState? state = null)
    {
        SkinTabButton.Pressed = CurrentLayer == SurgeryLayer.Skin;
        TissueTabButton.Pressed = CurrentLayer == SurgeryLayer.Tissue;
        OrganTabButton.Pressed = CurrentLayer == SurgeryLayer.Organ;

        // Disable layer buttons if not accessible (skin is always accessible)
        if (state != null)
        {
            TissueTabButton.Disabled = !state.CanAccessTissueLayer;
            OrganTabButton.Disabled = !state.CanAccessOrganLayer;
        }
    }
}

