// SPDX-FileCopyrightText: 2025 terkala <appleorange64@gmail.com>
//
// SPDX-License-Identifier: MIT

using Content.Client.UserInterface.Controls;
using Content.Shared.Medical.Surgery;
using Content.Shared._Shitmed.Targeting;
using Content.Shared.Body.Components;
using Content.Shared.Body.Part;
using Content.Shared.Body.Systems;
using Content.Shared.Humanoid;
using Content.Client.Medical.Surgery.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.Graphics;
using Robust.Shared.Graphics.RSI;
using Robust.Shared.Utility;
using System.Numerics;
using System.Linq;
using System;

namespace Content.Client.Medical.Surgery;

[GenerateTypedNameReferences]
public sealed partial class SurgeryWindow : Content.Client.UserInterface.Controls.FancyWindow
{
    public event Action<SurgeryLayer>? OnLayerChanged;
    public event Action<NetEntity>? OnStepSelected;
    public event Action<NetEntity, bool>? OnToolMethodSelected; // step, isImprovised
    public event Action<TargetBodyPart?>? OnBodyPartSelected;

    public SurgeryLayer CurrentLayer { get; private set; } = SurgeryLayer.Skin;
    private readonly IEntityManager _entMan;
    private readonly SpriteSystem _spriteSystem;
    private readonly SharedBodySystem _bodySystem;
    private readonly Dictionary<TargetBodyPart, TextureButton> _bodyPartControls;
    internal TargetBodyPart? _selectedBodyPart; // Internal so SurgeryBui can access it
    private TargetBodyPart? _pendingSelection; // Track selection we just sent to server
    private EntityUid? _spriteViewEntity;
    private EntityUid? _lastBodyEntity;
    private readonly Dictionary<TargetBodyPart, string> _highlightLayerIds = new();

    public SurgeryWindow(IEntityManager entMan)
    {
        RobustXamlLoader.Load(this);
        _entMan = entMan;
        _spriteSystem = _entMan.System<SpriteSystem>();
        _bodySystem = _entMan.System<SharedBodySystem>();

        // Map buttons to TargetBodyPart - sprite is standing up, so buttons map directly to body parts
        _bodyPartControls = new Dictionary<TargetBodyPart, TextureButton>
        {
            { TargetBodyPart.Head, HeadButton },
            { TargetBodyPart.Torso, ChestButton },
            { TargetBodyPart.LeftArm, LeftArmButton },
            { TargetBodyPart.LeftHand, LeftHandButton },
            { TargetBodyPart.RightArm, RightArmButton },
            { TargetBodyPart.RightHand, RightHandButton },
            { TargetBodyPart.LeftLeg, LeftLegButton },
            { TargetBodyPart.LeftFoot, LeftFootButton },
            { TargetBodyPart.RightLeg, RightLegButton },
            { TargetBodyPart.RightFoot, RightFootButton },
        };

        foreach (var bodyPartButton in _bodyPartControls)
        {
            bodyPartButton.Value.MouseFilter = MouseFilterMode.Stop;
            bodyPartButton.Value.OnPressed += _ => SetActiveBodyPart(bodyPartButton.Key);
        }

        SkinTabButton.OnPressed += _ => SetLayer(SurgeryLayer.Skin);
        TissueTabButton.OnPressed += _ => SetLayer(SurgeryLayer.Tissue);
        OrganTabButton.OnPressed += _ => SetLayer(SurgeryLayer.Organ);

        // Default to torso selection
        _selectedBodyPart = TargetBodyPart.Torso;
        UpdateBodyPartButtons();
    }

    private void SetActiveBodyPart(TargetBodyPart part)
    {
        _selectedBodyPart = part;
        _pendingSelection = part; // Track that we just selected this
        UpdateBodyPartButtons();
        UpdateBodyPartHighlight();
        OnBodyPartSelected?.Invoke(part);
    }

    private void UpdateBodyPartHighlight()
    {
        if (_spriteViewEntity == null || !_entMan.TryGetComponent<SpriteComponent>(_spriteViewEntity, out var sprite))
            return;

        var spriteEntity = _spriteViewEntity.Value;

        // Remove all existing highlight layers
        foreach (var layerId in _highlightLayerIds.Values)
        {
            if (_spriteSystem.LayerMapTryGet((spriteEntity, sprite), layerId, out var layerIndex, false))
            {
                _spriteSystem.LayerMapRemove((spriteEntity, sprite), layerId);
                _spriteSystem.RemoveLayer((spriteEntity, sprite), layerIndex);
            }
        }
        _highlightLayerIds.Clear();

        // Add highlight for selected body part
        if (_selectedBodyPart.HasValue)
        {
            var part = _selectedBodyPart.Value;
            string enumName = Enum.GetName(typeof(TargetBodyPart), part) ?? "torso";
            string partName = enumName.ToLowerInvariant();
            string layerId = $"surgery-highlight-{partName}";
            
            // Find the corresponding body part layer to copy its texture and position
            HumanoidVisualLayers? bodyPartLayer = part switch
            {
                TargetBodyPart.Head => HumanoidVisualLayers.Head,
                TargetBodyPart.Torso => HumanoidVisualLayers.Chest,
                TargetBodyPart.LeftArm => HumanoidVisualLayers.LArm,
                TargetBodyPart.LeftHand => HumanoidVisualLayers.LHand,
                TargetBodyPart.RightArm => HumanoidVisualLayers.RArm,
                TargetBodyPart.RightHand => HumanoidVisualLayers.RHand,
                TargetBodyPart.LeftLeg => HumanoidVisualLayers.LLeg,
                TargetBodyPart.LeftFoot => HumanoidVisualLayers.LFoot,
                TargetBodyPart.RightLeg => HumanoidVisualLayers.RLeg,
                TargetBodyPart.RightFoot => HumanoidVisualLayers.RFoot,
                _ => null
            };
            
            if (!bodyPartLayer.HasValue)
                return;
            
            try
            {
                // Try to find the body part layer
                if (!_spriteSystem.TryGetLayer((spriteEntity, sprite), bodyPartLayer.Value, out var bodyPartLayerData, false))
                {
                    // Try by string name as fallback
                    var layerName = bodyPartLayer.Value.ToString();
                    if (!_spriteSystem.LayerMapTryGet((spriteEntity, sprite), layerName, out var namedLayerIndex, false) ||
                        !_spriteSystem.TryGetLayer((spriteEntity, sprite), namedLayerIndex, out bodyPartLayerData, false))
                    {
                        return; // Can't find the layer, skip highlighting
                    }
                }
                
                // Get the texture from the body part layer
                var bodyPartTexture = bodyPartLayerData.Texture;
                if (bodyPartTexture == null)
                {
                    // Try to get texture from RSI state if available
                    if (bodyPartLayerData.RSI != null && bodyPartLayerData.State != null)
                    {
                        var rsiState = bodyPartLayerData.RSI[bodyPartLayerData.State];
                        if (rsiState != null)
                        {
                            // Get frame 0 of the current direction
                            bodyPartTexture = rsiState.GetFrame(RsiDirection.South, 0);
                        }
                    }
                    
                    if (bodyPartTexture == null)
                        return; // No texture available
                }
                
                // Create a new layer with the same texture as the body part, positioned at the same offset
                // This layer will render on top since it's added last to the sprite component
                // This layer will render on top since it's added last
                var layerIndex = _spriteSystem.AddTextureLayer((spriteEntity, sprite), bodyPartTexture);
                _spriteSystem.LayerMapSet((spriteEntity, sprite), layerId, layerIndex);
                
                // Copy the offset from the original layer
                _spriteSystem.LayerSetOffset((spriteEntity, sprite), layerIndex, bodyPartLayerData.Offset);
                
                // Copy other transform properties to match the original layer
                _spriteSystem.LayerSetRotation((spriteEntity, sprite), layerIndex, bodyPartLayerData.Rotation);
                _spriteSystem.LayerSetScale((spriteEntity, sprite), layerIndex, bodyPartLayerData.Scale);
                
                // Set color to solid red - this will make the entire texture appear as pure red
                // Since sprite base color is white (1,1,1,1) and layer color is (1,0,0,1),
                // the result will be (1,0,0,1) which is pure red
                var solidRed = new Color(1.0f, 0.0f, 0.0f, 1.0f);
                _spriteSystem.LayerSetColor((spriteEntity, sprite), layerIndex, solidRed);
                
                // Make sure the layer is visible
                _spriteSystem.LayerSetVisible((spriteEntity, sprite), layerIndex, true);
                
                _highlightLayerIds[part] = layerId;
            }
            catch
            {
                // If anything fails, skip highlighting for this part
                return;
            }
        }
    }

    private void UpdateBodyPartButtons()
    {
        foreach (var (part, button) in _bodyPartControls)
        {
            button.Pressed = part == _selectedBodyPart;
        }
    }

    private void SetLayer(SurgeryLayer layer)
    {
        CurrentLayer = layer;
        OnLayerChanged?.Invoke(layer);
        // Update buttons will be called from UpdateState with proper state
    }

    public void UpdateState(SurgeryBoundUserInterfaceState state)
    {
        // Update sprite view with body entity
        var bodyPartEntity = _entMan.GetEntity(state.BodyPart);
        EntityUid? bodyEntity = null;
        
        if (_entMan.TryGetComponent<BodyPartComponent>(bodyPartEntity, out var bodyPartComp))
        {
            bodyEntity = bodyPartComp.Body;
        }
        else if (_entMan.TryGetComponent<BodyComponent>(bodyPartEntity, out _))
        {
            // If the BodyPart is actually the body itself
            bodyEntity = bodyPartEntity;
        }

        bool needsSpriteCopy = false;
        if (bodyEntity != null)
        {
            // Create or update sprite view entity for highlighting
            if (_spriteViewEntity == null || _entMan.Deleted(_spriteViewEntity))
            {
                _spriteViewEntity = _entMan.Spawn("AlertSpriteView");
            }

            // Only copy sprite if the body entity changed (to avoid clearing highlights on every update)
            needsSpriteCopy = _lastBodyEntity != bodyEntity.Value;
            if (needsSpriteCopy)
            {
                // Copy body sprite to our view entity
                if (_entMan.TryGetComponent<SpriteComponent>(bodyEntity.Value, out var bodySprite) &&
                    _entMan.TryGetComponent<SpriteComponent>(_spriteViewEntity, out var viewSprite))
                {
                    _spriteSystem.CopySprite((bodyEntity.Value, bodySprite), (_spriteViewEntity.Value, viewSprite));
                    
                    // Note: SpriteView.Scale in XAML handles the scaling, so we don't need to scale layers here
                    // Highlights will be re-applied below if we have a selection
                }
                _lastBodyEntity = bodyEntity.Value;
            }

            SpriteView.SetEntity(_spriteViewEntity.Value);
            // Force sprite to stand up (South direction) to match button layout
            SpriteView.OverrideDirection = Robust.Shared.Maths.Direction.South;
            SpriteView.Visible = true;
            PartView.Visible = true;
        }
        else
        {
            SpriteView.Visible = false;
            PartView.Visible = false;
            _lastBodyEntity = null;
        }

        // Update selected body part from state, but only if state has a value
        // Don't override user selection if we just sent a selection message (pending)
        bool selectionChanged = false;
        if (state.SelectedTargetBodyPart.HasValue)
        {
            var targetPart = state.SelectedTargetBodyPart.Value;
            
            // If we have a pending selection, only accept state updates that match it
            // This prevents race conditions where an old state update resets our selection
            if (_pendingSelection.HasValue)
            {
                if (targetPart == _pendingSelection.Value)
                {
                    // Server confirmed our selection - clear pending flag
                    _pendingSelection = null;
                    if (targetPart != _selectedBodyPart)
                    {
                        _selectedBodyPart = targetPart;
                        selectionChanged = true;
                    }
                }
                // Otherwise ignore this state update - our selection is still pending
            }
            else if (targetPart != _selectedBodyPart)
            {
                // No pending selection, accept state update
                _selectedBodyPart = targetPart;
                selectionChanged = true;
            }
        }
        else if (_selectedBodyPart == null && !_pendingSelection.HasValue)
        {
            // Only set default to Torso if we don't have a selection yet (initial state)
            // and we're not waiting for a selection to be confirmed
            _selectedBodyPart = TargetBodyPart.Torso;
            selectionChanged = true;
        }
        // If state is null but we have a selection or pending selection, keep it
        
        // Update UI if selection changed or if sprite was copied (highlights need re-applying)
        if (selectionChanged || needsSpriteCopy)
        {
            UpdateBodyPartButtons();
            UpdateBodyPartHighlight();
        }

        // Update layer buttons - disable if not accessible
        UpdateLayerButtons(state);

        // Clear and refresh the step list - steps are already filtered by the selected body part on the server
        // When a body part is clicked, the server filters steps for that body part and sends them in the state
        StepsContainer.RemoveAllChildren();

        List<NetEntity> steps;
        bool layerAccessible = false;

        // Get steps for the current layer - these are already filtered by the selected body part (state.SelectedBodyPart)
        switch (CurrentLayer)
        {
            case SurgeryLayer.Skin:
                steps = state.SkinSteps; // Steps filtered for selected body part
                layerAccessible = true; // Skin layer is always accessible
                break;
            case SurgeryLayer.Tissue:
                steps = state.TissueSteps; // Steps filtered for selected body part
                layerAccessible = state.CanAccessTissueLayer; // Use state flag
                break;
            case SurgeryLayer.Organ:
                steps = state.OrganSteps; // Steps filtered for selected body part
                layerAccessible = state.CanAccessOrganLayer; // Use state flag
                break;
            default:
                steps = new List<NetEntity>();
                break;
        }

        if (!layerAccessible)
        {
            var label = new Robust.Client.UserInterface.Controls.Label 
            { 
                Text = Loc.GetString("surgery-window-layer-inaccessible", 
                    ("layer", Loc.GetString($"surgery-window-layer-{CurrentLayer.ToString().ToLower()}")))
            };
            StepsContainer.AddChild(label);
            return;
        }

        if (steps.Count == 0)
        {
            var label = new Robust.Client.UserInterface.Controls.Label { Text = Loc.GetString("surgery-window-no-steps") };
            StepsContainer.AddChild(label);
            return;
        }

        foreach (var stepNetEntity in steps)
        {
            // Get operation info for this step
            state.StepOperationInfo.TryGetValue(stepNetEntity, out var operationInfo);

            // Create hierarchical step control
            var stepControl = new SurgeryStepControl(
                _entMan,
                stepNetEntity,
                operationInfo,
                CurrentLayer
            );

            stepControl.OnStepSelected += (step) => OnStepSelected?.Invoke(step);
            stepControl.OnToolMethodSelected += (step, isImprovised) => OnToolMethodSelected?.Invoke(step, isImprovised);

            StepsContainer.AddChild(stepControl);
        }
    }

    private void UpdateLayerButtons(SurgeryBoundUserInterfaceState? state = null)
    {
        SkinTabButton.Pressed = CurrentLayer == SurgeryLayer.Skin;
        TissueTabButton.Pressed = CurrentLayer == SurgeryLayer.Tissue;
        OrganTabButton.Pressed = CurrentLayer == SurgeryLayer.Organ;

        // Disable layer buttons if not accessible (skin is always accessible)
        if (state != null)
        {
            TissueTabButton.Disabled = !state.CanAccessTissueLayer;
            OrganTabButton.Disabled = !state.CanAccessOrganLayer;
        }
    }

    [Obsolete("Controls should only be removed from UI tree instead of being disposed")]
    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        // Clean up the sprite view entity - it's only used for UI rendering, not world rendering
        if (disposing && _spriteViewEntity != null && !_entMan.Deleted(_spriteViewEntity))
        {
            _entMan.QueueDeleteEntity(_spriteViewEntity);
            _spriteViewEntity = null;
        }
    }
}

