// SPDX-FileCopyrightText: 2025 terkala <appleorange64@gmail.com>
//
// SPDX-License-Identifier: MIT

using Content.Client.UserInterface.Controls;
using Content.Shared.Medical.CyberLimb;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Medical.CyberLimb.UI;

[GenerateTypedNameReferences]
public sealed partial class CyberneticsSelectionWindow : FancyWindow
{
    public event Action<NetEntity>? OnCyberneticSelected;

    public CyberneticsSelectionWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(CyberneticsSelectionState state)
    {
        CyberneticsListContainer.RemoveAllChildren();

        if (state.AvailableCybernetics.Count == 0)
        {
            var label = new Label { Text = "No cybernetics with storage found." };
            CyberneticsListContainer.AddChild(label);
            return;
        }

        foreach (var cyberneticData in state.AvailableCybernetics)
        {
            var buttonText = cyberneticData.CyberneticName;
            if (cyberneticData.IsPanelOpen)
            {
                buttonText += " (Panel Open)";
            }

            var button = new Button
            {
                Text = buttonText,
                HorizontalExpand = true
            };

            button.OnPressed += _ =>
            {
                OnCyberneticSelected?.Invoke(cyberneticData.Cybernetic);
            };

            CyberneticsListContainer.AddChild(button);
        }
    }
}
