// SPDX-FileCopyrightText: 2025 terkala <appleorange64@gmail.com>
//
// SPDX-License-Identifier: MIT

using Content.Client.UserInterface.Controls;
using Content.Shared.Medical.CyberLimb;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.IoC;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;

namespace Content.Client.Medical.CyberLimb.UI;

[GenerateTypedNameReferences]
public sealed partial class CyberArmRadialMenu : RadialMenu
{
    [Dependency] private readonly IResourceCache _resourceCache = default!;
    [Dependency] private readonly ILocalizationManager _locManager = default!;
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly SpriteSystem _spriteSystem = default!;

    public event Action<NetEntity>? ItemSelected;
    public event Action? OpenHandSelected;

    private EntityUid _owner;
    private NetEntity? _activeItem;

    public CyberArmRadialMenu()
    {
        IoCManager.Instance!.InjectDependencies(this);
        RobustXamlLoader.Load(this);
    }

    public void SetEntity(EntityUid uid)
    {
        _owner = uid;
    }

    public void UpdateState(CyberArmRadialMenuState state)
    {
        _activeItem = state.ActiveItem;
        Refresh(state.AvailableItems);
    }

    private void Refresh(List<CyberArmItemData> items)
    {
        var main = FindControl<RadialContainer>("Main");
        if (main == null)
            return;

        // Clear existing buttons
        main.RemoveAllChildren();

        // Add "Open Hand" button in center (if there are items or if there's an active item)
        if (items.Count > 0 || _activeItem != null)
        {
            var openHandButton = new CyberArmMenuButton
            {
                SetSize = new Vector2(64f, 64f),
                ToolTip = "Open Hand",
                IsOpenHand = true,
            };

            // Use a simple icon or text for "open hand"
            var label = new Label
            {
                Text = Loc.GetString("cyber-arm-open-hand"),
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
            };
            openHandButton.AddChild(label);

            openHandButton.OnButtonUp += _ =>
            {
                OpenHandSelected?.Invoke();
                Close();
            };

            main.AddChild(openHandButton);
        }

        // Add buttons for each item
        foreach (var itemData in items)
        {
            var button = new CyberArmMenuButton
            {
                SetSize = new Vector2(64f, 64f),
                ToolTip = itemData.ItemName,
                ItemEntity = itemData.Item,
                IsOpenHand = false,
            };

            // Add sprite if available
            if (!string.IsNullOrEmpty(itemData.SpritePath))
            {
                var spriteSpec = new SpriteSpecifier.Texture(new ResPath(itemData.SpritePath));
                var sprite = _spriteSystem.Frame0(spriteSpec);
                if (sprite != null)
                {
                    var tex = new TextureRect
                    {
                        VerticalAlignment = VAlignment.Center,
                        HorizontalAlignment = HAlignment.Center,
                        Texture = sprite,
                        TextureScale = new Vector2(2f, 2f),
                    };
                    button.AddChild(tex);
                }
            }
            else
            {
                // Fallback: try to get sprite from entity
                if (_entityManager.TryGetEntity(itemData.Item, out var entity))
                {
                    var metaData = _entityManager.GetComponent<MetaDataComponent>(entity.Value);
                    var sprite = _spriteSystem.GetPrototypeIcon(metaData.EntityPrototype?.ID ?? "");
                    if (sprite != null)
                    {
                        var tex = new TextureRect
                        {
                            VerticalAlignment = VAlignment.Center,
                            HorizontalAlignment = HAlignment.Center,
                            Texture = sprite.Default,
                            TextureScale = new Vector2(2f, 2f),
                        };
                        button.AddChild(tex);
                    }
                }
            }

            // Highlight if this is the active item
            if (itemData.Item == _activeItem)
            {
                button.Modulate = Color.Yellow;
            }

            button.OnButtonUp += _ =>
            {
                ItemSelected?.Invoke(itemData.Item);
                Close();
            };

            main.AddChild(button);
        }
    }
}

public sealed class CyberArmMenuButton : RadialMenuTextureButtonWithSector
{
    public NetEntity? ItemEntity { get; set; }
    public bool IsOpenHand { get; set; }
}
