// SPDX-FileCopyrightText: 2025 terkala <appleorange64@gmail.com>
//
// SPDX-License-Identifier: MIT

using Content.Shared.Medical.Limb.Targeting;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;

namespace Content.Client.Medical.Limb.Targeting.Widgets;

/// <summary>
/// Paper-doll UI widget for targeting body parts.
/// Allows players to select Head, Torso, Arms, or Legs for targeting.
/// When Arms or Legs is selected, both left and right sides are highlighted.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class TargetingControl : Control
{
    [Dependency] private readonly IEntityManager _entMan = default!;
    [Dependency] private readonly IPlayerManager _playerManager = default!;
    [Dependency] private readonly SpriteSystem _spriteSystem = default!;
    
    private EntityUid? _spriteViewEntity;
    private readonly Dictionary<TargetBodyPart, TextureButton> _bodyPartButtons = new();

    public TargetingControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        // Map buttons to target body parts
        // Note: Individual left/right arm/leg buttons map to Arms/Legs respectively
        _bodyPartButtons[TargetBodyPart.Head] = HeadButton;
        _bodyPartButtons[TargetBodyPart.Torso] = TorsoButton;
        // Arms buttons - both left and right arm buttons map to Arms
        _bodyPartButtons[TargetBodyPart.Arms] = LeftArmButton; // Use left as primary
        // Legs buttons - both left and right leg buttons map to Legs
        _bodyPartButtons[TargetBodyPart.Legs] = LeftLegButton; // Use left as primary

        // Set up button handlers
        HeadButton.OnPressed += _ => OnBodyPartSelected(TargetBodyPart.Head);
        TorsoButton.OnPressed += _ => OnBodyPartSelected(TargetBodyPart.Torso);
        
        // Both arm buttons select Arms
        LeftArmButton.OnPressed += _ => OnBodyPartSelected(TargetBodyPart.Arms);
        RightArmButton.OnPressed += _ => OnBodyPartSelected(TargetBodyPart.Arms);
        
        // Both leg buttons select Legs
        LeftLegButton.OnPressed += _ => OnBodyPartSelected(TargetBodyPart.Legs);
        RightLegButton.OnPressed += _ => OnBodyPartSelected(TargetBodyPart.Legs);
    }

    public event Action<TargetBodyPart>? OnBodyPartPressed;

    private void OnBodyPartSelected(TargetBodyPart target)
    {
        OnBodyPartPressed?.Invoke(target);
        UpdateButtonStates(target);
    }

    public void UpdateTargetSelection(TargetBodyPart selectedTarget)
    {
        UpdateButtonStates(selectedTarget);
        UpdateSpriteView();
    }

    private void UpdateButtonStates(TargetBodyPart selectedTarget)
    {
        // Update button pressed states
        // When Arms is selected, both arm buttons should be pressed
        // When Legs is selected, both leg buttons should be pressed
        HeadButton.Pressed = selectedTarget == TargetBodyPart.Head;
        TorsoButton.Pressed = selectedTarget == TargetBodyPart.Torso;
        
        bool armsSelected = selectedTarget == TargetBodyPart.Arms;
        LeftArmButton.Pressed = armsSelected;
        RightArmButton.Pressed = armsSelected;
        
        bool legsSelected = selectedTarget == TargetBodyPart.Legs;
        LeftLegButton.Pressed = legsSelected;
        RightLegButton.Pressed = legsSelected;
    }

    private void UpdateSpriteView()
    {
        if (_playerManager.LocalEntity is not { } player)
            return;

        if (_entMan.TryGetComponent<SpriteComponent>(player, out var playerSprite))
        {
            // Update sprite view entity if needed
            // This would show the player's body with highlighting for selected parts
        }
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        UpdateSpriteView();
    }
}
