// SPDX-FileCopyrightText: 2025 terkala <appleorange64@gmail.com>
//
// SPDX-License-Identifier: MIT

using Content.Client.UserInterface.Controls;
using Content.Shared.Medical.Autodoc;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Client.GameObjects;

namespace Content.Client.Medical.Autodoc;

[GenerateTypedNameReferences]
    public sealed partial class AutodocWindow : Content.Client.UserInterface.Controls.FancyWindow
    {
        public event Action<AutodocMode>? OnModeSelected;
        public event Action<NetEntity>? OnOrganSelected;
        public event Action? OnActivate;

        private AutodocMode _currentMode = AutodocMode.OrganImplant;
        private readonly IEntityManager _entMan;

        public AutodocWindow(EntityUid owner, IEntityManager entMan)
        {
            RobustXamlLoader.Load(this);
            _entMan = entMan;

            OrganImplantButton.OnPressed += _ => SetMode(AutodocMode.OrganImplant);
            MedicalCareButton.OnPressed += _ => SetMode(AutodocMode.MedicalCare);
            OrganRemovalButton.OnPressed += _ => SetMode(AutodocMode.OrganRemoval);
            ActivateButton.OnPressed += _ => OnActivate?.Invoke();
        }

    private void SetMode(AutodocMode mode)
    {
        _currentMode = mode;
        OnModeSelected?.Invoke(mode);
        UpdateModeButtons();
    }

    private void UpdateModeButtons()
    {
        OrganImplantButton.Pressed = _currentMode == AutodocMode.OrganImplant;
        MedicalCareButton.Pressed = _currentMode == AutodocMode.MedicalCare;
        OrganRemovalButton.Pressed = _currentMode == AutodocMode.OrganRemoval;
    }

    public void UpdateState(AutodocBoundUserInterfaceState state)
    {
        _currentMode = state.Mode;
        UpdateModeButtons();

        // Show/hide organ list for removal mode
        if (state.Mode == AutodocMode.OrganRemoval && state.HasPatient)
        {
            OrganListContainer.Visible = true;
            UpdateOrganList(state.AvailableOrgans);
        }
        else
        {
            OrganListContainer.Visible = false;
        }

        ActivateButton.Disabled = !state.HasPatient || state.IsActive;

        if (!state.HasPatient)
        {
            StatusLabel.Text = Loc.GetString("autodoc-window-status-no-patient");
            ActivateButton.Disabled = true;
        }
        else if (state.IsActive)
        {
            StatusLabel.Text = Loc.GetString("autodoc-window-status-active");
        }
        else
        {
            StatusLabel.Text = Loc.GetString("autodoc-window-status-ready");
            
            // Check mode-specific requirements
            if (state.Mode == AutodocMode.OrganImplant && !state.HasOrganInSlot)
            {
                ActivateButton.Disabled = true;
            }
            else if (state.Mode == AutodocMode.OrganRemoval && state.SelectedOrgan == null)
            {
                ActivateButton.Disabled = true;
            }
        }
    }

    private void UpdateOrganList(List<NetEntity> organs)
    {
        OrganListContainer.RemoveAllChildren();

        if (organs.Count == 0)
        {
            var label = new Robust.Client.UserInterface.Controls.Label { Text = Loc.GetString("autodoc-window-no-organs") };
            OrganListContainer.AddChild(label);
            return;
        }

        foreach (var organNetEntity in organs)
        {
            var organEntity = _entMan.GetEntity(organNetEntity);
            var button = new Robust.Client.UserInterface.Controls.Button
            {
                Text = _entMan.GetComponent<MetaDataComponent>(organEntity).EntityName,
                HorizontalExpand = true
            };

            button.OnPressed += _ => OnOrganSelected?.Invoke(organNetEntity);
            OrganListContainer.AddChild(button);
        }
    }
}

